In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('gurgaon_properties_missing_value_imputation.csv')

In [3]:
df.head()

,society,price,sector,price_per_sqft,bedRoom,bathroom,balcony,floorNum,agePossession,property_type,built_up_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,independent,15.50,sector 43,28233.0,5,6,3,3.0,Moderately Old,house,5490.00,1,1,1,1,0,0,76
1,trisara our homes 3,0.38,sohna road,6312.0,2,2,2,1.0,Relatively New,flat,602.00,0,0,0,0,0,0,0
2,sare green parc phase 3,0.70,sector 92,5279.0,3,2,2,4.0,Relatively New,flat,1325.00,0,0,0,0,0,0,56
3,emaar gurgaon greens,1.60,sector 102,9696.0,3,3,3,8.0,Relatively New,flat,1315.00,0,0,0,0,0,0,46
4,emaar mgf the palm drive,3.98,sector 66,18090.0,3,4,3+,2.0,Moderately Old,flat,2200.11,0,1,0,0,0,2,123

In [4]:
train_df = df.drop(columns=['society','price_per_sqft'])

In [5]:
train_df.head()

,price,sector,bedRoom,bathroom,balcony,floorNum,agePossession,property_type,built_up_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,15.50,sector 43,5,6,3,3.0,Moderately Old,house,5490.00,1,1,1,1,0,0,76
1,0.38,sohna road,2,2,2,1.0,Relatively New,flat,602.00,0,0,0,0,0,0,0
2,0.70,sector 92,3,2,2,4.0,Relatively New,flat,1325.00,0,0,0,0,0,0,56
3,1.60,sector 102,3,3,3,8.0,Relatively New,flat,1315.00,0,0,0,0,0,0,46
4,3.98,sector 66,3,4,3+,2.0,Moderately Old,flat,2200.11,0,1,0,0,0,2,123

In [6]:
def categorize_luxury(score):
    if 0 <= score < 50:
        return "Low"
    elif 50 <= score < 150:
        return "Medium"
    elif 150 <= score <= 175:
        return "High"
    else:
        return None

In [7]:
train_df['luxury_category'] = train_df['luxury_score'].apply(categorize_luxury)

In [8]:
def categorize_floor(floor):
    if 0 <= floor <= 2:
        return "Low Floor"
    elif 3 <= floor <= 10:
        return "Mid Floor"
    elif 11 <= floor <= 51:
        return "High Floor"
    else:
        return None

In [9]:
train_df['floor_category'] = train_df['floorNum'].apply(categorize_floor)

In [10]:
train_df.head()

,price,sector,bedRoom,bathroom,balcony,floorNum,agePossession,property_type,built_up_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score,luxury_category,floor_category
0,15.50,sector 43,5,6,3,3.0,Moderately Old,house,5490.00,1,1,1,1,0,0,76,Medium,Mid Floor
1,0.38,sohna road,2,2,2,1.0,Relatively New,flat,602.00,0,0,0,0,0,0,0,Low,Low Floor
2,0.70,sector 92,3,2,2,4.0,Relatively New,flat,1325.00,0,0,0,0,0,0,56,Medium,Mid Floor
3,1.60,sector 102,3,3,3,8.0,Relatively New,flat,1315.00,0,0,0,0,0,0,46,Low,Mid Floor
4,3.98,sector 66,3,4,3+,2.0,Moderately Old,flat,2200.11,0,1,0,0,0,2,123,Medium,Low Floor

In [11]:
train_df = train_df.drop(columns=['floorNum','luxury_score'])

In [12]:
train_df = train_df.drop(columns = ['pooja room', 'study room', 'others'])

In [13]:
train_df.head()

,price,sector,bedRoom,bathroom,balcony,agePossession,property_type,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,15.50,sector 43,5,6,3,Moderately Old,house,5490.00,1,1,0,Medium,Mid Floor
1,0.38,sohna road,2,2,2,Relatively New,flat,602.00,0,0,0,Low,Low Floor
2,0.70,sector 92,3,2,2,Relatively New,flat,1325.00,0,0,0,Medium,Mid Floor
3,1.60,sector 102,3,3,3,Relatively New,flat,1315.00,0,0,0,Low,Mid Floor
4,3.98,sector 66,3,4,3+,Moderately Old,flat,2200.11,1,0,2,Medium,Low Floor

train_df.to_csv('gurgaon_properties_post_feature_selection_v2.csv', index=False)