In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties.csv')

In [6]:
df.shape

(3961, 20)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   society          3960 non-null   object
 2   price            3941 non-null   float64
 3   price_per_sqft   3941 non-null   float64
 4   area             3941 non-null   float64
 5   areaWithType     3961 non-null   object
 6   bedRoom          3961 non-null   int64
 7   bathroom         3961 non-null   int64
 8   balcony          3961 non-null   object
 9   additionalRoom   3961 non-null   object
 10  address          3950 non-null   object
 11  floorNum         3940 non-null   object
 12  facing           2784 non-null   object
 13  agePossession    3960 non-null   object
 14  nearbyLocations  3754 non-null   object
 15  description      3961 non-null   object
 16  furnishDetails   2929 non-null   object
 17  features         3252 non-null   object
 18  rating           3511 non-null   object
 19  property_type    964 non-null    object
dtypes: float64(3), int64(2), object(15)
memory usage: 619.0+ KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['property_type'] = df['property_type'].fillna('flat')

In [15]:
df.isnull().sum()

property_name         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
property_type         0
dtype: int64

In [16]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [17]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
0,5 Bedroom House for sale in B Block Sushant Lo...,independent,15.50,B Block Sushant Lok Phase 1,28233.0,5490.00,Plot area 610(510.04 sq.m.),5,6,3,"pooja room,study room,servant room,store room","B Block Sushant Lok Phase 1, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Iffco chowk metro station', 'Huda city centr...","Basement , ground floor, first floor and terra...",[],"['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4.5 out of...",house
1,2 BHK Flat in Sohna,trisara our homes 3,0.38,Sohna,6312.0,602.03,Built Up area: 602 (55.93 sq.m.),2,2,2,not availaible,"Sohna Sector 6, Sohna, Gurgaon, Haryana",1st of 1 Floors,NaN,undefined,"['Metro Station', 'Gyanchand Market', 'Rajiv C...",Best in class property available at sector 6 s...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",flat
2,3 BHK Flat in Sector 92 Gurgaon,sare green parc phase 3,0.70,Sector 92,5279.0,1326.01,Super Built up area 1326(123.19 sq.m.)Built Up...,3,2,2,not availaible,"Sector 92 Gurgaon, Gurgaon, Haryana",4th of 19 Floors,NaN,1 to 5 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Property at 4th floor ne facing,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle4 out of 5...",flat
3,3 BHK Flat in Sector 102 Gurgaon,emaar gurgaon greens,1.60,Sector 102,9696.0,1650.17,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,not availaible,"Sector 102 Gurgaon, Gurgaon, Haryana",8th of 14 Floors,NaN,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...",[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of...",flat
4,3 BHK Flat in Sector 66 Gurgaon,emaar mgf the palm drive,3.98,Sector 66,18090.0,2200.11,Super Built up area 2200(204.39 sq.m.),3,4,3+,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",2nd of 17 Floors,South-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Beautiful two side open property, facing kids ...","['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ...",flat

In [18]:
df['sector'] = df['sector'].str.lower()

In [19]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
0,5 Bedroom House for sale in B Block Sushant Lo...,independent,15.50,b block sushant lok phase 1,28233.0,5490.00,Plot area 610(510.04 sq.m.),5,6,3,"pooja room,study room,servant room,store room","B Block Sushant Lok Phase 1, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Iffco chowk metro station', 'Huda city centr...","Basement , ground floor, first floor and terra...",[],"['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4.5 out of...",house
1,2 BHK Flat in Sohna,trisara our homes 3,0.38,sohna,6312.0,602.03,Built Up area: 602 (55.93 sq.m.),2,2,2,not availaible,"Sohna Sector 6, Sohna, Gurgaon, Haryana",1st of 1 Floors,NaN,undefined,"['Metro Station', 'Gyanchand Market', 'Rajiv C...",Best in class property available at sector 6 s...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",flat
2,3 BHK Flat in Sector 92 Gurgaon,sare green parc phase 3,0.70,sector 92,5279.0,1326.01,Super Built up area 1326(123.19 sq.m.)Built Up...,3,2,2,not availaible,"Sector 92 Gurgaon, Gurgaon, Haryana",4th of 19 Floors,NaN,1 to 5 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Property at 4th floor ne facing,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle4 out of 5...",flat
3,3 BHK Flat in Sector 102 Gurgaon,emaar gurgaon greens,1.60,sector 102,9696.0,1650.17,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,not availaible,"Sector 102 Gurgaon, Gurgaon, Haryana",8th of 14 Floors,NaN,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...",[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of...",flat
4,3 BHK Flat in Sector 66 Gurgaon,emaar mgf the palm drive,3.98,sector 66,18090.0,2200.11,Super Built up area 2200(204.39 sq.m.),3,4,3+,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",2nd of 17 Floors,South-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Beautiful two side open property, facing kids ...","['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ...",flat

In [20]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
nirvana country                                               53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
laxman vihar                                                  27
sector 54                                                     27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
dlf phase 3                                                   22
sector 111                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
sector 76                                                     14
dlf phase 5                                                   14
rajendra park                                                 14
sector 52                                                     14
sector 1 imt manesar                                          14
sector 3                                                      14
sector 53                                                     14
gwal pahari                                                   14
sector 46                                                     13
laxman vihar phase 2                                          13
sector 36a                                                    13
sector 93                                                     12
sector 39                                                     12
sohna road                                                    12
uppals southend                                               12
sector 38                                                     12
sector 50                                                     12
sector 31                                                     12
sector 47                                                     11
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 4                                                       9
sector 95a                                                     9
ashok vihar phase 2                                            9
south city 1                                                   9
sector 55                                                      9
sector 57                                                      8
malibu town                                                    8
sector 43                                                      8
sector 89 a                                                    8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
sector 59                                                      8
sector 40                                                      8
dwarka expressway                                              8
sector 10a                                                     8
palam vihar extension                                          8
sector 11                                                      7
sector 26                                                      7
sector 58                                                      7
mianwali colony                                                7
sector 51                                                      7
surat nagar 1                                                  7
sector 36 sohna                                                7
new colony                                                     7
jyoti park                                                     6
sector 1                                                       6
jacobpura                                                      6
ashok vihar                                                    6
rajiv nagar                                                    6
sector 5                                                       6
subhash nagar                                                  5
sector 80                                                      5
chakkarpur                                                     5
sector 30                                                      5
dayanand colony                                                5
sector 9                                                       5
greenwood city                                                 5
sector 23a                                                     5
sushant lok phase 2                                            5
arjun nagar                                                    5
sector 28                                                      5
ansal plaza                                                    5
manesar                                                        5
saraswati vihar                                                5
new palam vihar                                                5
sector 105                                                     5
sector 2                                                       5
bhondsi                                                        4
sector 12a                                                     4
ravi nagar                                                     4
sector 36                                                      4
dharam colony                                                  4
baldev nagar                                                   4
suncity                                                        4
adarsh nagar                                                   4
sector 17                                                      4
sector 12                                                      4
garhi harsaru                                                  4
bhim nagar                                                     4
devilal colony                                                 4
madanpuri                                                      4
vishnu garden                                                  4
shivaji nagar                                                  4
surya vihar                                                    4
krishna colony                                                 4
sector 3a                                                      4
sector 45                                                      4
imt manesar                                                    4
sector 6                                                       4
shivpuri                                                       4
new                                                            4
valley view estate                                             4
sector 73                                                      3
patel nagar                                                    3
laxmi garden                                                   3
sector 15                                                      3
maruti kunj                                                    3
sector 17a                                                     3
sector 110 a                                                   3
a block sushant lok phase 1                                    3
sector 88b                                                     3
gandhi nagar                                                   3
mg road                                                        3
sector 23                                                      3
shakti nagar                                                   3
sector 27                                                      3
sector 17b                                                     3
b block sushant lok phase 1                                    3
prem nagar                                                     3
sector 8                                                       3
bissar                                                         2
west rajiv nagar                                               2
mohan nagar                                                    2
acharya puri                                                   2
farukhnagar                                                    2
faridabad road                                                 2
new basti                                                      2
nars                                                           2
sector-2 sohna                                                 2
new palam vihar phase 2                                        2
rajiv chowk                                                    2
rosewood                                                       2
manohar nagar                                                  2
bhawani enclave                                                2
lajpat nagar                                                   2
sector 24                                                      2
sector 21                                                      2
block a surya vihar                                            2
sector 15 part 1                                               2
samaspur                                                       2
daulatabad                                                     2
new palam vihar phase 1                                        2
sector 41                                                      2
sector-11 sohna                                                2
sushant lok                                                    2
golf course ext road                                           2
hira nagar                                                     2
golf course road                                               2
surat nagar phase 2                                            2
mayfield garden                                                2
sohna  road                                                    2
iffco chowk                                                    2
pratap nagar                                                   2
shanti nagar                                                   2
sispal vihar                                                   2
sheetla colony                                                 2
ambience island                                                2
sector 15 part 2                                               2
shankar vihar                                                  2
sector 32                                                      2
, delhi ncr                                                    2
surat nagar                                                    2
urban estate, sector 5                                         1
hno 13 sagar enclave sura                                      1
rattan garden                                                  1
khandsa                                                        1
jacobpura near sadar bazar                                     1
gopal nagar, garhi ghasita, sonipat                            1
sec 3 bhim vihar part 1 bhimgher kheri                         1
carterpuri village                                             1
pataudi road                                                   1
begampur khatola                                               1
nirvana country pocket h                                       1
sai kunj                                                       1
saraswati enclave                                              1
sector 42                                                      1
near euro                                                      1
sultanpur                                                      1
sector 37b                                                     1
damdma                                                         1
naharpur rupa                                                  1
ashok vihar phase i                                            1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector 5 chowk                                                 1
g block dlf city phase 1                                       1
saroop garden rajendra park                                    1
godrej aria , sector 79 ,                                      1
sadar bazar                                                    1
sector 17c                                                     1
bhora kalan                                                    1
new colony, sector 7                                           1
block g sector-57                                              1
sector-5 sohna                                                 1
hsiidc plot sector 1 imt manesar                               1
bhimgarh kheri phase 3                                         1
sector 13                                                      1
south city                                                     1
sector 4 urban estate                                          1
near pataudi chowk                                             1
shivji park colony                                             1
sector-7 hous                                                  1
block h ashok vihar phase iii extension                        1
tekchand nagar                                                 1
ashok vihar phase 3                                            1
b1 block sector 57                                             1
sector 21a faridabad                                           1
vir nagar                                                      1
civil l                                                        1
mahavir pura                                                   1
lucknow                                                        1
sector-35 sohna                                                1
part 3 sector 5                                                1
heritage city                                                  1
rajiv colony                                                   1
ats marigold                                                   1
near nand hospital                                             1
udyog vihar phase 1                                            1
cyber city                                                     1
near khandsa road                                              1
laxman vihar, railway road,                                    1
om nagar                                                       1
old delhi road, opp sector-14                                  1
sector-5 sheetla colony                                        1
sector 9b                                                      1
alipur                                                         1
kheri                                                          1
kanahi                                                         1
ram nagar                                                      1
laxmna vihar, phase 2                                          1
bptp                                                           1
dhankot                                                        1
mahalaxmi garden, rajendra place                               1
ravi nager basai road                                          1
huda saraswati vihar                                           1
ansal's palam vihar                                            1
jat colony,fazilpur/taj nagar road                             1
near sector 1 market                                           1
park view                                                      1
new jyoti park                                                 1
sector 37a                                                     1
garauli kalan                                                  1
anand garden, sector-105                                       1
v block dlf phase 3                                            1
Name: count, dtype: int64

In [21]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [22]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [23]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [24]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [25]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [26]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [27]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [28]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [29]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 37c                     53
sector 70                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 112                     24
sector 57                      24
sector 105                     23
sector 88a                     23
sector 14                      23
sector 33                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 82a                     20
sector 22                      20
sector 3                       20
sector 47                      19
sector 78                      19
sector 74                      18
gwal pahari                    18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 110                     16
sector 99                      16
sector 60                      15
sector 63                      15
sector 1 manesar               14
sector 52                      14
sector 76                      14
sector 53                      14
sector 55                      14
sector 36a                     13
sector 9                       13
sector 46                      13
sector 6                       13
sector 4 phase 2               13
sector 31                      12
sector 38                      12
sector 39                      12
sohna road road                12
sector 93                      12
sector 41                      11
sector 9a                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 1a manesar              10
manesar                         9
sector 3 phase 2                9
sector 45                       9
sector 95a                      9
sector 59                       8
sector 89 a                     8
sector 40                       8
sector 17                       8
c block sector 43               8
sector 2 extension              8
sector 8                        8
dwarka expressway               8
sector 23                       8
sector 10a                      8
sector 36 sohna road            7
sector 51                       7
sector 58                       7
sector 5                        6
sector 1                        6
sector 21                       6
sector 30                       5
sector 80                       5
new sector 2                    5
sector 23a                      5
sector 3a                       4
sector 12a                      4
new                             4
sector 36                       4
patel nagar                     3
sector 27                       3
maruti kunj                     3
sector 17b                      3
b block sector 43               3
sector 15                       3
sector 17a                      3
a block sector 43               3
sector 110 a                    3
sector 73                       3
sector 88b                      3
Name: count, dtype: int64

In [31]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\3954173571.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [32]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\600812590.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [33]:
df[df['sector'] == 'new']

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
51,2 BHK Flat in New Gurgaon,takshila heights sector 37 c,0.67,new,5583.0,1200.07,Super Built up area 1200(111.48 sq.m.),2,2,2,not availaible,"New Gurgaon, Gurgaon, Haryana",3rd of 12 Floors,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN,flat
906,4 BHK Flat in New Gurgaon,dlf 76,4.00,new,11428.0,3500.18,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4th of 10 Floors,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN,flat
2473,2 BHK Flat in New Gurgaon,green court,0.38,new,5507.0,690.03,Carpet area: 690 (64.1 sq.m.),2,2,1,not availaible,"New Gurgaon, Gurgaon, Haryana",7th of 15 Floors,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN,flat
3102,4 BHK Flat in New Gurgaon,sare homes,0.85,new,4786.0,1776.01,Super Built up area 1776(165 sq.m.),4,4,3,not availaible,"New Gurgaon, Gurgaon, Haryana",3rd of 4 Floors,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN,flat

In [34]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [35]:
df[df['sector'] == 'new sector 2']

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
1631,3 Bedroom House for sale in New Palam Vihar,independent,1.00,new sector 2,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",house
2830,2 Bedroom House for sale in New Palam Vihar,my home,0.34,new sector 2,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5...",house
3133,2 BHK Flat in New Palam Vihar,my home,0.22,new sector 2,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not availaible,"New Palam Vihar, Gurgaon, Haryana",1st of 4 Floors,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",flat
3178,2 BHK Flat in New Palam Vihar,my home,0.28,new sector 2,3166.0,884.4,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2nd of 3 Floors,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ...",flat
3496,2 BHK Flat in New Palam Vihar,ompee k s residency,1.60,new sector 2,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not availaible,"New Palam Vihar, Gurgaon, Haryana",1st of 4 Floors,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",flat

In [36]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [37]:
df.shape

(3803, 21)

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type
0,5 Bedroom House for sale in B Block Sushant Lo...,independent,15.50,sector 43,28233.0,5490.00,Plot area 610(510.04 sq.m.),5,6,3,"pooja room,study room,servant room,store room","B Block Sushant Lok Phase 1, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Iffco chowk metro station', 'Huda city centr...","Basement , ground floor, first floor and terra...",[],"['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4.5 out of...",house
1,2 BHK Flat in Sohna,trisara our homes 3,0.38,sohna road,6312.0,602.03,Built Up area: 602 (55.93 sq.m.),2,2,2,not availaible,"Sohna Sector 6, Sohna, Gurgaon, Haryana",1st of 1 Floors,NaN,undefined,"['Metro Station', 'Gyanchand Market', 'Rajiv C...",Best in class property available at sector 6 s...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",flat
2,3 BHK Flat in Sector 92 Gurgaon,sare green parc phase 3,0.70,sector 92,5279.0,1326.01,Super Built up area 1326(123.19 sq.m.)Built Up...,3,2,2,not availaible,"Sector 92 Gurgaon, Gurgaon, Haryana",4th of 19 Floors,NaN,1 to 5 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Property at 4th floor ne facing,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle4 out of 5...",flat
3,3 BHK Flat in Sector 102 Gurgaon,emaar gurgaon greens,1.60,sector 102,9696.0,1650.17,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,not availaible,"Sector 102 Gurgaon, Gurgaon, Haryana",8th of 14 Floors,NaN,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...",[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of...",flat
4,3 BHK Flat in Sector 66 Gurgaon,emaar mgf the palm drive,3.98,sector 66,18090.0,2200.11,Super Built up area 2200(204.39 sq.m.),3,4,3+,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",2nd of 17 Floors,South-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Beautiful two side open property, facing kids ...","['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Power Back-up', 'In...","['Green Area5 out of 5', 'Construction4.5 out ...",flat

In [40]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\1453130667.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [41]:
df.sample(5)

,society,price,sector,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,property_type
1945,m3m urbana,0.95,sector 67,10895.0,871.96,Built Up area: 826 (76.74 sq.m.),1,1,1,not availaible,17th of 17 Floors,South-West,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Kamal Hospital a...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",flat
66,ss,2.09,sector 85,7432.0,2812.16,Super Built up area 2812(261.24 sq.m.)Built Up...,4,4,3,"pooja room,study room,servant room",8th of 15 Floors,South-East,1 to 5 Year Old,"['Orris Community Center', 'Indian Oil', 'Essa...","['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...",flat
2177,emaar imperial gardens,1.91,sector 102,9550.0,2000.00,Super Built up area 2000(185.81 sq.m.)Carpet a...,3,4,2,"servant room,study room",17th of 20 Floors,East,1 to 5 Year Old,"['Satya The Hive Mall', 'Gurugram Road', 'Dwar...","['5 Fan', '1 Exhaust Fan', '10 Light', '1 Chim...","['Centrally Air Conditioned', 'Security / Fire...",flat
2669,independent,0.70,sector 12,6034.0,1160.00,Plot area 1160(107.77 sq.m.),3,3,0,not available,1.0,North-East,1 to 5 Year Old,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","['2 Fan', '2 Light', '1 Chimney', 'No AC', 'No...","['Private Garden / Terrace', 'Water Storage', ...",house
3451,independent,1.45,sector 55,241666.0,60.00,Plot area 60(5.57 sq.m.),4,4,3+,store room,4.0,East,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...","['1 Wardrobe', 'No AC', 'No Bed', 'No Chimney'...","['Private Garden / Terrace', 'Water purifier',...",house

In [42]:
df.duplicated().sum()

np.int64(121)

In [44]:
df.floorNum

0                            3.0
1              1st   of 1 Floors
2             4th   of 19 Floors
3             8th   of 14 Floors
4             2nd   of 17 Floors
5             8th   of 19 Floors
6                            4.0
7             1st   of 19 Floors
8              3rd   of 4 Floors
9                            2.0
10            5th   of 20 Floors
12                           3.0
13                           3.0
14            5th   of 13 Floors
16             2nd   of 3 Floors
17            8th   of 24 Floors
18           11st   of 21 Floors
19             4th   of 8 Floors
20           19th   of 19 Floors
21            9th   of 15 Floors
22            5th   of 14 Floors
23            1st   of 26 Floors
24            6th   of 19 Floors
25           19th   of 19 Floors
26            4th   of 26 Floors
27            9th   of 13 Floors
28            8th   of 14 Floors
29           12nd   of 12 Floors
30            8th   of 23 Floors
31           16th   of 16 Floors
32             1st   of 4 Floors
33           11st   of 15 Floors
34                           2.0
35           31st   of 40 Floors
36           18th   of 21 Floors
37            8th   of 19 Floors
38            Ground of 4 Floors
39             4th   of 5 Floors
40            9th   of 40 Floors
41            9th   of 27 Floors
42            5th   of 12 Floors
43            7th   of 18 Floors
44           11st   of 19 Floors
45                           1.0
46            1st   of 15 Floors
47            7th   of 14 Floors
48                           1.0
49           12nd   of 18 Floors
50            6th   of 18 Floors
51            3rd   of 12 Floors
52            1st   of 13 Floors
53            9th   of 23 Floors
54           12nd   of 34 Floors
55             2nd   of 4 Floors
56           14th   of 19 Floors
57                           2.0
58           14th   of 14 Floors
59             4th   of 4 Floors
60             1st   of 1 Floors
61                           4.0
62                           2.0
63           10th   of 11 Floors
64             4th   of 4 Floors
65             3rd   of 4 Floors
66            8th   of 15 Floors
67            3rd   of 26 Floors
68           17th   of 33 Floors
69            5th   of 23 Floors
70            3rd   of 10 Floors
71                           3.0
72           Ground of 14 Floors
73            6th   of 11 Floors
74            6th   of 26 Floors
75             2nd   of 3 Floors
76             1st   of 2 Floors
77             8th   of 9 Floors
78             7th   of 8 Floors
79           10th   of 18 Floors
80             1st   of 2 Floors
81                           4.0
82                           4.0
83                           3.0
84            1st   of 11 Floors
85                           1.0
86            4th   of 15 Floors
87                           3.0
88           11st   of 16 Floors
89                           2.0
90                           3.0
91            1st   of 17 Floors
92             9th   of 9 Floors
93             6th   of 9 Floors
94             6th   of 8 Floors
95            3rd   of 18 Floors
96                           3.0
97           Ground of 23 Floors
98            8th   of 29 Floors
99            3rd   of 14 Floors
100          10th   of 28 Floors
101          33rd   of 42 Floors
102           8th   of 26 Floors
103          16th   of 18 Floors
104                          1.0
105                          5.0
106                          4.0
107            3rd   of 4 Floors
108                          2.0
109          23rd   of 23 Floors
110           5th   of 10 Floors
111          Ground of 14 Floors
112                          1.0
113           7th   of 15 Floors
114           5th   of 26 Floors
115                          2.0
116           9th   of 14 Floors
118          12nd   of 14 Floors
119           4th   of 10 Floors
120           7th   of 13 Floors
121          24th   of 39 Floors
122           8th   of 14 Floors
123          23rd   of 26 Floors
124          11st   of 14 Floors
125                          NaN
126                          1.0
127           9th   of 14 Floors
128                          4.0
129          14th   of 29 Floors
130            1st   of 4 Floors
131           7th   of 15 Floors
132           3rd   of 13 Floors
133          10th   of 12 Floors
134           8th   of 12 Floors
135           8th   of 14 Floors
136                          3.0
137           Ground of 1 Floors
138                          3.0
139                          4.0
140          14th   of 19 Floors
141                          4.0
142           4th   of 19 Floors
143           6th   of 10 Floors
144           8th   of 13 Floors
145          15th   of 28 Floors
146          15th   of 15 Floors
147                          1.0
148           7th   of 18 Floors
149           7th   of 15 Floors
150           5th   of 14 Floors
151          12nd   of 26 Floors
152            3rd   of 9 Floors
153                          2.0
154           6th   of 12 Floors
155          11st   of 11 Floors
156          20th   of 20 Floors
157           5th   of 11 Floors
158          10th   of 28 Floors
159                          NaN
160           6th   of 12 Floors
162                          3.0
163            2nd   of 2 Floors
164           7th   of 15 Floors
165           8th   of 18 Floors
166          11st   of 14 Floors
167                          5.0
168            3rd   of 4 Floors
169          10th   of 29 Floors
170          18th   of 51 Floors
171                          2.0
172           1st   of 19 Floors
173                          2.0
174          19th   of 19 Floors
175                          2.0
176           3rd   of 14 Floors
177           7th   of 14 Floors
178           1st   of 18 Floors
180            1st   of 4 Floors
181          16th   of 18 Floors
182           5th   of 22 Floors
183            4th   of 4 Floors
184          15th   of 17 Floors
185            4th   of 4 Floors
186           5th   of 34 Floors
187           7th   of 21 Floors
188                          3.0
189           4th   of 13 Floors
190            9th   of 9 Floors
191           5th   of 14 Floors
192                          4.0
193          12nd   of 29 Floors
194            3rd   of 3 Floors
195           4th   of 13 Floors
196           6th   of 18 Floors
197                          3.0
198          15th   of 20 Floors
199                          NaN
200            4th   of 4 Floors
201           4th   of 13 Floors
202           5th   of 14 Floors
203          10th   of 20 Floors
204                          2.0
205           7th   of 14 Floors
206                          3.0
207           4th   of 14 Floors
208           3rd   of 30 Floors
209            2nd   of 4 Floors
210                          3.0
211          10th   of 33 Floors
212            2nd   of 4 Floors
213                          3.0
214            3rd   of 4 Floors
215            9th   of 9 Floors
216           6th   of 19 Floors
217                          4.0
218                          2.0
219          Ground of 12 Floors
220           4th   of 14 Floors
221            2nd   of 4 Floors
222           Ground of 1 Floors
223                          3.0
224           2nd   of 15 Floors
225           7th   of 14 Floors
226          16th   of 45 Floors
227            1st   of 7 Floors
228          11st   of 12 Floors
229                          3.0
230           7th   of 29 Floors
231           8th   of 14 Floors
232                          3.0
233           9th   of 10 Floors
234            4th   of 6 Floors
235                          2.0
236          12nd   of 21 Floors
237           5th   of 14 Floors
238          16th   of 19 Floors
239           2nd   of 10 Floors
240            2nd   of 2 Floors
241           1st   of 12 Floors
242           7th   of 14 Floors
243          14th   of 27 Floors
244          16th   of 20 Floors
245          23rd   of 36 Floors
246            2nd   of 4 Floors
247                          3.0
248                          3.0
250           2nd   of 22 Floors
251           9th   of 28 Floors
252          15th   of 22 Floors
253                          2.0
254           3rd   of 19 Floors
255          15th   of 15 Floors
256                          NaN
257            4th   of 4 Floors
258          15th   of 19 Floors
259          Ground of 14 Floors
260                          2.0
261          12nd   of 17 Floors
263          10th   of 14 Floors
264          16th   of 16 Floors
265            2nd   of 3 Floors
266          10th   of 14 Floors
267            7th   of 8 Floors
268                          4.0
269           9th   of 15 Floors
271          12nd   of 13 Floors
272                          1.0
273                          1.0
274                          3.0
275           5th   of 12 Floors
276           7th   of 40 Floors
277            3rd   of 4 Floors
278          13rd   of 30 Floors
279                          3.0
280                          1.0
281           1st   of 14 Floors
282           2nd   of 19 Floors
283                          4.0
284           2nd   of 14 Floors
285          18th   of 32 Floors
286           8th   of 14 Floors
287           3rd   of 13 Floors
288          12nd   of 12 Floors
289           7th   of 15 Floors
290            2nd   of 3 Floors
291          10th   of 15 Floors
292          14th   of 19 Floors
293                          2.0
294           1st   of 14 Floors
295           9th   of 14 Floors
296                          3.0
297                          3.0
298                          3.0
299                          3.0
300           5th   of 15 Floors
301          15th   of 40 Floors
302          Ground of 18 Floors
303           1st   of 20 Floors
304           3rd   of 32 Floors
305          11st   of 12 Floors
306                          2.0
307                          2.0
308          19th   of 19 Floors
309          18th   of 40 Floors
310                          2.0
311           8th   of 18 Floors
312           2nd   of 16 Floors
313            9th   of 9 Floors
314          15th   of 22 Floors
315                          3.0
316           2nd   of 15 Floors
317          14th   of 14 Floors
318           8th   of 10 Floors
320                          2.0
321                          3.0
322           3rd   of 19 Floors
323            1st   of 4 Floors
324           2nd   of 20 Floors
325           7th   of 12 Floors
326           7th   of 19 Floors
327          11st   of 20 Floors
328           2nd   of 16 Floors
329          13rd   of 47 Floors
330                          3.0
332           8th   of 22 Floors
333                          3.0
334           6th   of 16 Floors
335           9th   of 14 Floors
336          10th   of 14 Floors
337        Basement of 13 Floors
339           9th   of 20 Floors
340          15th   of 23 Floors
341           8th   of 13 Floors
342          23rd   of 29 Floors
343                          2.0
344          14th   of 21 Floors
345            1st   of 5 Floors
346           8th   of 14 Floors
347          17th   of 22 Floors
348           8th   of 19 Floors
349                          3.0
350           8th   of 26 Floors
351           8th   of 13 Floors
353           6th   of 10 Floors
354           5th   of 15 Floors
355          17th   of 20 Floors
356            3rd   of 4 Floors
357                          3.0
358           5th   of 18 Floors
359           8th   of 16 Floors
360                          2.0
361            2nd   of 4 Floors
362           Ground of 1 Floors
363            1st   of 5 Floors
364          12nd   of 14 Floors
365          Ground of 16 Floors
367                          2.0
368           6th   of 15 Floors
369                         12.0
370           8th   of 14 Floors
371           6th   of 14 Floors
372           6th   of 26 Floors
373                          3.0
374            3rd   of 9 Floors
375            2nd   of 4 Floors
376           2nd   of 11 Floors
377                          3.0
378            1st   of 3 Floors
379           6th   of 12 Floors
380           6th   of 12 Floors
381          11st   of 13 Floors
382          12nd   of 15 Floors
383          12nd   of 39 Floors
384           6th   of 19 Floors
385                          2.0
386                          4.0
387            1st   of 4 Floors
388          18th   of 24 Floors
389                          3.0
390            2nd   of 4 Floors
391          14th   of 27 Floors
392           6th   of 10 Floors
393           3rd   of 13 Floors
394                          1.0
395           6th   of 18 Floors
396           5th   of 25 Floors
397          14th   of 29 Floors
398          12nd   of 24 Floors
399           4th   of 14 Floors
400          12nd   of 13 Floors
401          17th   of 17 Floors
402           7th   of 14 Floors
403           8th   of 19 Floors
404            6th   of 6 Floors
405                          3.0
406           4th   of 12 Floors
407           3rd   of 27 Floors
409            2nd   of 4 Floors
410           5th   of 18 Floors
411           3rd   of 12 Floors
412                          3.0
413                          1.0
414          13rd   of 19 Floors
415            2nd   of 3 Floors
416                          2.0
417           7th   of 17 Floors
418           Ground of 1 Floors
419          11st   of 14 Floors
420           8th   of 19 Floors
421           6th   of 19 Floors
422           6th   of 20 Floors
423           4th   of 20 Floors
424                          4.0
425          15th   of 31 Floors
426            1st   of 4 Floors
427                          1.0
428                          3.0
429            2nd   of 2 Floors
431            4th   of 4 Floors
432           1st   of 19 Floors
433                          2.0
434          10th   of 17 Floors
435            4th   of 4 Floors
436                          2.0
437                          2.0
438           5th   of 14 Floors
439            1st   of 3 Floors
440            1st   of 4 Floors
441          14th   of 16 Floors
442                          1.0
443           4th   of 39 Floors
444                          3.0
445           9th   of 24 Floors
446           8th   of 19 Floors
447           8th   of 27 Floors
448          10th   of 12 Floors
449            3rd   of 4 Floors
450                          3.0
451          11st   of 19 Floors
452          14th   of 16 Floors
453            44   of 47 Floors
454           9th   of 40 Floors
455           9th   of 30 Floors
456                          4.0
457          14th   of 14 Floors
458           3rd   of 16 Floors
459            3rd   of 4 Floors
460            4th   of 4 Floors
461                          3.0
462                          4.0
463            1st   of 4 Floors
464           8th   of 16 Floors
465          10th   of 14 Floors
466            1st   of 4 Floors
467                          1.0
468           6th   of 18 Floors
469            1st   of 1 Floors
471            1st   of 3 Floors
472            2nd   of 4 Floors
474            2nd   of 4 Floors
475           7th   of 21 Floors
476           5th   of 12 Floors
477          14th   of 15 Floors
478            6th   of 6 Floors
479           9th   of 18 Floors
480           6th   of 13 Floors
482           2nd   of 13 Floors
483           2nd   of 14 Floors
484                          1.0
485                          3.0
486           2nd   of 15 Floors
487                          2.0
488            3rd   of 6 Floors
489           9th   of 13 Floors
491           4th   of 15 Floors
492          11st   of 29 Floors
493                          2.0
494            3rd   of 4 Floors
495           3rd   of 15 Floors
496           2nd   of 10 Floors
497           3rd   of 22 Floors
498           1st   of 24 Floors
499           9th   of 14 Floors
500            2nd   of 4 Floors
501          22nd   of 30 Floors
502          23rd   of 26 Floors
503           5th   of 15 Floors
504           7th   of 18 Floors
506            3rd   of 5 Floors
507            1st   of 4 Floors
508          20th   of 26 Floors
509          16th   of 26 Floors
510            2nd   of 2 Floors
511                          4.0
512           5th   of 12 Floors
513          Ground of 14 Floors
514            9th   of 9 Floors
515                          2.0
516           5th   of 12 Floors
517           8th   of 12 Floors
518            3rd   of 4 Floors
519          11st   of 14 Floors
520                          1.0
521            1st   of 1 Floors
522            3rd   of 5 Floors
524           5th   of 14 Floors
525          12nd   of 18 Floors
526                          2.0
527                          4.0
528          11st   of 27 Floors
529            2nd   of 5 Floors
530          11st   of 30 Floors
531           7th   of 21 Floors
533            9th   of 9 Floors
534                          2.0
535                          4.0
536          15th   of 32 Floors
537            1st   of 4 Floors
538                          3.0
539           8th   of 21 Floors
540            3rd   of 4 Floors
541          15th   of 18 Floors
542           8th   of 19 Floors
543                          2.0
544          10th   of 18 Floors
545                          3.0
546                          3.0
547           8th   of 14 Floors
548          15th   of 18 Floors
549           3rd   of 13 Floors
550          12nd   of 26 Floors
551           1st   of 14 Floors
552                          1.0
553          24th   of 32 Floors
555            1st   of 1 Floors
556            4th   of 4 Floors
557           6th   of 12 Floors
558           3rd   of 25 Floors
559                          2.0
560          14th   of 14 Floors
561          14th   of 14 Floors
562           9th   of 13 Floors
564          10th   of 19 Floors
565            4th   of 4 Floors
568          12nd   of 22 Floors
569           1st   of 14 Floors
570                          2.0
571           8th   of 14 Floors
572          14th   of 14 Floors
573           5th   of 29 Floors
574           4th   of 15 Floors
575                          2.0
576                          4.0
577          12nd   of 19 Floors
578           5th   of 16 Floors
579            2nd   of 4 Floors
580          14th   of 19 Floors
581                          3.0
582           8th   of 12 Floors
583            1st   of 4 Floors
584            3rd   of 5 Floors
585          15th   of 19 Floors
586          18th   of 35 Floors
587           7th   of 32 Floors
588                          1.0
589            1st   of 4 Floors
590           7th   of 20 Floors
591           2nd   of 19 Floors
592                          4.0
593           Ground of 4 Floors
594            1st   of 2 Floors
595                          1.0
596           7th   of 14 Floors
597                          2.0
598                          4.0
599            9th   of 9 Floors
600                          2.0
602            3rd   of 3 Floors
603           7th   of 18 Floors
604                          2.0
605                          1.0
606          10th   of 21 Floors
607           4th   of 17 Floors
608          15th   of 32 Floors
609           8th   of 14 Floors
610            7th   of 7 Floors
612           2nd   of 20 Floors
613            3rd   of 4 Floors
614           9th   of 16 Floors
615          14th   of 32 Floors
616                          4.0
617          11st   of 13 Floors
618           5th   of 14 Floors
619          14th   of 24 Floors
620                          1.0
621           5th   of 20 Floors
622           6th   of 21 Floors
623          11st   of 14 Floors
625            1st   of 1 Floors
626          16th   of 19 Floors
627           4th   of 21 Floors
628           4th   of 28 Floors
629                          1.0
630           5th   of 14 Floors
631           5th   of 15 Floors
632          15th   of 26 Floors
633          11st   of 25 Floors
634            1st   of 5 Floors

In [49]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_33612\208426714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [50]:
df.floorNum

0         3
1         1
2         4
3         8
4         2
5         8
6         4
7         1
8         3
9         2
10        5
12        3
13        3
14        5
16        2
17        8
18       11
19        4
20       19
21        9
22        5
23        1
24        6
25       19
26        4
27        9
28        8
29       12
30        8
31       16
32        1
33       11
34        2
35       31
36       18
37        8
38        0
39        4
40        9
41        9
42        5
43        7
44       11
45        1
46        1
47        7
48        1
49       12
50        6
51        3
52        1
53        9
54       12
55        2
56       14
57        2
58       14
59        4
60        1
61        4
62        2
63       10
64        4
65        3
66        8
67        3
68       17
69        5
70        3
71        3
72        0
73        6
74        6
75        2
76        1
77        8
78        7
79       10
80        1
81        4
82        4
83        3
84        1
85        1
86        4
87        3
88       11
89        2
90        3
91        1
92        9
93        6
94        6
95        3
96        3
97        0
98        8
99        3
100      10
101      33
102       8
103      16
104       1
105       5
106       4
107       3
108       2
109      23
110       5
111       0
112       1
113       7
114       5
115       2
116       9
118      12
119       4
120       7
121      24
122       8
123      23
124      11
125     NaN
126       1
127       9
128       4
129      14
130       1
131       7
132       3
133      10
134       8
135       8
136       3
137       0
138       3
139       4
140      14
141       4
142       4
143       6
144       8
145      15
146      15
147       1
148       7
149       7
150       5
151      12
152       3
153       2
154       6
155      11
156      20
157       5
158      10
159     NaN
160       6
162       3
163       2
164       7
165       8
166      11
167       5
168       3
169      10
170      18
171       2
172       1
173       2
174      19
175       2
176       3
177       7
178       1
180       1
181      16
182       5
183       4
184      15
185       4
186       5
187       7
188       3
189       4
190       9
191       5
192       4
193      12
194       3
195       4
196       6
197       3
198      15
199     NaN
200       4
201       4
202       5
203      10
204       2
205       7
206       3
207       4
208       3
209       2
210       3
211      10
212       2
213       3
214       3
215       9
216       6
217       4
218       2
219       0
220       4
221       2
222       0
223       3
224       2
225       7
226      16
227       1
228      11
229       3
230       7
231       8
232       3
233       9
234       4
235       2
236      12
237       5
238      16
239       2
240       2
241       1
242       7
243      14
244      16
245      23
246       2
247       3
248       3
250       2
251       9
252      15
253       2
254       3
255      15
256     NaN
257       4
258      15
259       0
260       2
261      12
263      10
264      16
265       2
266      10
267       7
268       4
269       9
271      12
272       1
273       1
274       3
275       5
276       7
277       3
278      13
279       3
280       1
281       1
282       2
283       4
284       2
285      18
286       8
287       3
288      12
289       7
290       2
291      10
292      14
293       2
294       1
295       9
296       3
297       3
298       3
299       3
300       5
301      15
302       0
303       1
304       3
305      11
306       2
307       2
308      19
309      18
310       2
311       8
312       2
313       9
314      15
315       3
316       2
317      14
318       8
320       2
321       3
322       3
323       1
324       2
325       7
326       7
327      11
328       2
329      13
330       3
332       8
333       3
334       6
335       9
336      10
337       1
339       9
340      15
341       8
342      23
343       2
344      14
345       1
346       8
347      17
348       8
349       3
350       8
351       8
353       6
354       5
355      17
356       3
357       3
358       5
359       8
360       2
361       2
362       0
363       1
364      12
365       0
367       2
368       6
369      12
370       8
371       6
372       6
373       3
374       3
375       2
376       2
377       3
378       1
379       6
380       6
381      11
382      12
383      12
384       6
385       2
386       4
387       1
388      18
389       3
390       2
391      14
392       6
393       3
394       1
395       6
396       5
397      14
398      12
399       4
400      12
401      17
402       7
403       8
404       6
405       3
406       4
407       3
409       2
410       5
411       3
412       3
413       1
414      13
415       2
416       2
417       7
418       0
419      11
420       8
421       6
422       6
423       4
424       4
425      15
426       1
427       1
428       3
429       2
431       4
432       1
433       2
434      10
435       4
436       2
437       2
438       5
439       1
440       1
441      14
442       1
443       4
444       3
445       9
446       8
447       8
448      10
449       3
450       3
451      11
452      14
453      44
454       9
455       9
456       4
457      14
458       3
459       3
460       4
461       3
462       4
463       1
464       8
465      10
466       1
467       1
468       6
469       1
471       1
472       2
474       2
475       7
476       5
477      14
478       6
479       9
480       6
482       2
483       2
484       1
485       3
486       2
487       2
488       3
489       9
491       4
492      11
493       2
494       3
495       3
496       2
497       3
498       1
499       9
500       2
501      22
502      23
503       5
504       7
506       3
507       1
508      20
509      16
510       2
511       4
512       5
513       0
514       9
515       2
516       5
517       8
518       3
519      11
520       1
521       1
522       3
524       5
525      12
526       2
527       4
528      11
529       2
530      11
531       7
533       9
534       2
535       4
536      15
537       1
538       3
539       8
540       3
541      15
542       8
543       2
544      10
545       3
546       3
547       8
548      15
549       3
550      12
551       1
552       1
553      24
555       1
556       4
557       6
558       3
559       2
560      14
561      14
562       9
564      10
565       4
568      12
569       1
570       2
571       8
572      14
573       5
574       4
575       2
576       4
577      12
578       5
579       2
580      14
581       3
582       8
583       1
584       3
585      15
586      18
587       7
588       1
589       1
590       7
591       2
592       4
593       0
594       1
595       1
596       7
597       2
598       4
599       9
600       2
602       3
603       7
604       2
605       1
606      10
607       4
608      15
609       8
610       7
612       2
613       3
614       9
615      14
616       4
617      11
618       5
619      14
620       1
621       5
622       6
623      11
625       1
626      16
627       4
628       4
629       1
630       5
631       5
632      15
633      11
634       1
636      15
637       3
638       3
639      11
640       9
641      17
642       6
643      35
644       4
645      14
646       6
647       2
648      16
649       1
650      10
651      12
652       8
653      15
654      10
655       3
656       0
657       2
658       1
659      12
660       7
661       0
662       3
663       1
664       1
666      12
667       3
668       3
669       3
670       9
671       2
672      10
673       2
674       7
676       2
677       3
678      11
679       2
680       4
681       1
682      14
683       6
685      20
686      12
687       8
688      10
689       5
690       1
691       1
692      10
693       8
694       7
695       3
696       2
698       2
699       6
700       1
701      23
702       3
703       7
704       1
705      10
706       2
707       3
708       3
709      10
710       4
711       2
712      12
713       3
714       2
715       1
716       8
717       3
718       3
720       7
721       3
722       4
723       4
724       4
725      10
726      12
727      12
728      14
729       3
730       9
731      10
732       2
733      21
734      10
735       8
736       1
737       7
738       2
739       4
740       3
741       8
742       4
743       2
744      14
745      23
746       6
747      12
748       2
749       8
750       6
751       9
752       2
753      10
754       1
755       2
756      20
757       1
758       6
759       4
760       3
761       3
762       1
763       1
764       0
765       9
766       0
767       2
768       1
769       6
770       0
772       2
773      24
774       2
775       6
776       6
777      10
778      12
779       2
780       4
781       3
782      16
783       1
784       7
785      11
786       2
787      10
788       7
790       3
791      25
792       1
793      10
794       1
795       2
796      12
798       4
799       9
800      13
801       9
802       9
803       8
804       2
805       3
806       1
807       2
808       6
809       2
810       4
811       1
812       9
813       7
814       6
815       2
816      14
817      27
818      12
819       0
820      13
821       2
822       4
823      11
824       3
825      34
827      19
828       3
829       3
830       2
831       6
832       3
833       1
834       3
835       7
836       8
837       3
838      10
839       9
840       6
841      14
842       3
843      12
844       3
845       2
846       3
847      12
848       0
849       8
850      14
851       3
852       2
853      17
854       8
855       9
856       2
857       9
858      12
859       2
860       2
861       1
862       2
863      18
864      12
865       2
866      10
867     NaN
868       7
869      17
870      14
871       2
872      19
873       6
874       7
875       5
876       1
877       0
878       2
879      12
880       2
881      15
882       2
884       3
885      13
886       1
887       6
888       3
889       2
890      10
891       3
892       4
893      14
895      31
896       6
897      19
898       2
899       9
900       8
901       9
903       1
904      13
905       0
906       4
907       3
908       3
909       1
910       1
911       8
912       4
914       2
915       4
916      12
918       4
919      24
920       1
921       3
922       2
923       6
924       2
925      12
926       2
927      15
928      23
929       0
930      18
931       4
932       1
933      17
934       2
935      12
936      15
937      14
938       3
939       0
940       1
941      27
942       6
943       1
944       5
945      19
946       2
947      12
948       3
949      18
950       1
951       5
952       0
953       7
954       6
955       9
956       4
957       2
958       3
959       1
960      15
961      10
962      12
963       4
964       0
965       7
966       7
967       1
968       2
969       4
970       6
971      11
972       2
973       8
974      10
975       6
976       1
977       2
978       3
979       3
980       4
981       2
982      15
983      12
984       4
985       2
986       3
987       3
988      14
989       0
990       8
991       0
992       4
993       9
994       4
995       3
996       8
997      17
998      10
999      14
1000     18
1001      1
1002      7
1003     11
1004      5
1005      3
1006      2
1007      1
1008     10
1009      0
1010      4
1011     10
1012      4
1013      3
1014      4
1015      1
1016     12
1017     15
1018     12
1019     12
1020     18
1021      4
1022      4
1023      3
1024      9
1025     12
1026     12
1027      1
1028      6
1029      3
1030      1
1031      3
1032      4
1033      2
1034      2
1035      0
1037      8
1038      1
1039      6
1040      4
1041      1
1042     12
1043      1
1044      3
1045      2
1046      2
1047     10
1048      3
1049      9
1050      5
1051     12
1052     12
1053      3
1054      1
1055      0
1056      1
1058      7
1059    NaN
1061      3
1062      0
1063      7
1064      0
1065      0
1066     22
1067      9
1068      4
1069     17
1070      2
1072      8
1073      9
1075      3
1076      1
1077     33
1078      6
1079     16
1080      9
1081     17
1082     25
1083      3
1084      1
1085      9
1086     22
1087      3
1089     12
1090      1
1091      6
1092      5
1093     15
1094     20
1095     12
1096     12
1097     30
1098      2
1099     12
1100      5
1101      3
1102      2
1103      7
1104      2
1105      8
1106      7
1107      3
1108      1
1109     12
1110     14
1111      3
1112      0
1113      6
1114      1
1115      5
1116     10
1117      7
1118     14
1119      2
1121      7
1123     15
1124     11
1125      0
1126     11
1127      4
1128      9
1129     11
1130     15
1131     14
1132     10
1133     12
1134      5
1135      3
1136     10
1137      7
1138     17
1139      2
1140      3
1141      1
1142      3
1143      9
1144      9
1145      3
1146     10
1147      0
1148      4
1149      9
1150      1
1151      7
1152      8
1153     10
1154      2
1155     15
1156      1
1157      6
1158      2
1159      0
1160      2
1161      9
1164      3
1165      5
1166      4
1167      8
1168      8
1169     16
1170      9
1171     10
1172      0
1173     10
1174     11
1175      2
1176     13
1177      5
1178      7
1179     10
1180     10
1181      2
1182      5
1183      2
1184     16
1185     20
1186     12
1187      3
1188      3
1189     13
1190      1
1191      1
1192     12
1193      2
1194      6
1195     19
1196      1
1197      1
1199     10
1200      2
1201      2
1202     10
1203      2
1204     10
1205      3
1206     11
1207      3
1208      4
1209      1
1210      7
1211      2
1212     12
1214      0
1215      1
1216      3
1217      1
1218     12
1219      2
1220      2
1221      3
1222     10
1223      0
1224      1
1225      9
1226      3
1227      4
1228     10
1229     19
1230      5
1232      1
1233      4
1234      1
1235      2
1236     12
1237      9
1238      3
1239      4
1240      4
1241      9
1242     16
1243      1
1244      4
1245     16
1246      4
1247      3
1248      5
1249      3
1250      0
1251      0
1252      3
1253     31
1254     31
1255      2
1256      4
1257     14
1258      4
1259     11
1260      9
1261     14
1262      1
1263      8
1264      5
1265      3
1266      4
1267     16
1268      2
1269     33
1270      1
1271      7
1272      3
1273      3
1274      6
1275      0
1276      3
1277      3
1278      1
1279      1
1280      3
1281      9
1282     10
1283      7
1284      3
1286      3
1287      3
1288     14
1289      8
1290      5
1291     24
1292      1
1293      1
1294      1
1295     30
1296      7
1297     15
1298     11
1299      4
1300      2
1301      3
1302      7
1303      1
1304      2
1305      0
1306      9
1307     14
1308     16
1309      7
1310     24
1311      2
1312      2
1313      4
1314      3
1315     19
1316      5
1317      4
1318      1
1319      6
1320      1
1321      4
1322      0
1323     14
1324      1
1325      1
1326      3
1327      0
1328      6
1329      2
1330     12
1331      2
1332      9
1333      6
1334      2
1335      1
1336    NaN
1337     17
1338      3
1339     15
1340      1
1341      7
1342     22
1343     22
1344      8
1345      9
1346      8
1347     11
1348     10
1349     18
1350      4
1351     10
1352      0
1353      7
1354      1
1355      5
1356      3
1357     16
1358      3
1359      6
1360      8
1361      7
1362      2
1363      2
1364      2
1365     15
1366      1
1367     17
1368      8
1370      7
1371      7
1372      3
1373      1
1374     11
1375     19
1376      9
1378     16
1379      5
1380      9
1381     12
1382      1
1383      9
1384      1
1385     12
1386      6
1387      1
1388     11
1389      7
1390      4
1391      7
1392     27
1393      1
1394      8
1395      4
1396      3
1397      5
1398      5
1399     11
1400     26
1401      3
1402      3
1403      9
1404      2
1405      2
1406      4
1407      2
1409     15
1410      2
1411      1
1412      3
1413      2
1415     10
1416      4
1417     18
1419      0
1420      3
1421     15
1422      6
1423      0
1424      8
1425      0
1426      3
1427      9
1428     12
1429      9
1430      2
1431     11
1432      2
1433      7
1434      3
1435      0
1436     13
1437     15
1438      2
1439      9
1440     25
1441      3
1442      6
1443      2
1444      1
1445      7
1446     30
1447     15
1448      8
1449      1
1450      5
1451     11
1452      6
1453      1
1454     40
1455      3
1456     14
1457      9
1458      2
1459     12
1460      1
1461      3
1462      4
1463      2
1464      3
1465     22
1466      5
1467      5
1468     14
1469      6
1470      3
1471     15
1472      3
1473     11
1474      1
1475      8
1476      6
1477      5
1478      2
1479      4
1480      3
1481      3
1482      8
1484      3
1485     12
1486      9
1487      1
1488     18
1489      0
1490      1
1491     23
1492      4
1493      7
1494      4
1495      3
1496      0
1497     11
1498      4
1499      3
1500      8
1501      6
1502      4
1503     17
1504      9
1505     15
1506     10
1507      3
1508      2
1509     12
1510      9
1511      0
1512      3
1513      4
1514      3
1515     13
1516      8
1517      5
1518      4
1519      3
1520      2
1521     11
1522     13
1523      4
1524      7
1525      3
1526      4
1527      3
1528      8
1530      3
1531      1
1532      3
1533     20
1534      7
1535      5
1536     11
1537      4
1538      2
1539     11
1540      1
1541     12
1542     12
1543     11
1544     14
1545      2
1546     10
1547      5
1548      6
1550      4
1551      8
1552     11
1553      2
1554      3
1555     12
1556      8
1557     14
1558      3
1559      2
1560      9
1561      2
1562     14
1563      6
1564     12
1565     19
1566      5
1567     10
1568      9
1569      7
1570      2
1572     21
1573      2
1574     12
1575      3
1576      7
1577      0
1578      8
1579      7
1580      8
1581      3
1582     15
1583      6
1584      2
1585      2
1586     14
1587     14
1588     17
1589      1
1590      0
1591      2
1592      3
1593      5
1594     28
1595      5
1596     10
1598      4
1599     16
1600      1
1601      7
1602      5
1603      6
1604      0
1605      3
1606      5
1607     10
1608      6
1609      1
1610      3
1611      7
1612     10
1613      4
1614      0
1616     18
1617      1
1618      1
1619      0
1620      8
1621     17
1622      5
1623      2
1624     13
1625     27
1626      4
1627      7
1628     10
1629     16
1630      5
1631      1
1632      2
1633      4
1634      3
1635      2
1636      2
1637     11
1638      4
1639     17
1640      3
1641     11
1643      7
1644      1
1645      2
1646      2
1647      7
1648      2
1649      2
1651      8
1652     11
1653      3
1654      4
1655      2
1656      7
1657      2
1658      1
1659      6
1660      0
1661    NaN
1662      3
1663     12
1664      2
1665    NaN
1666     11
1667     10
1668      4
1669      9
1670      2
1671      3
1673      3
1674      7
1675      2
1676      1
1677    NaN
1679      4
1680     14
1681      8
1682      4
1683      4
1685      1
1686      7
1687      4
1688      6
1689      9
1690      2
1691      0
1692      7
1693      2
1694      4
1695      7
1696      7
1697      8
1698      3
1699     12
1700      9
1701      2
1702      6
1703      2
1704      3
1705      7
1706      6
1707      9
1708    NaN
1709      4
1710      3
1711      9
1712     14
1713      9
1714      4
1715      0
1716      3
1717      7
1718      0
1719     17
1720      8
1721      3
1723     10
1724     12
1725      2
1726      2
1727     10
1728     14
1729      6
1730      4
1732     13
1733     19
1734      9
1735      4
1736      1
1737     14
1738      0
1739     20
1740      1
1741      3

In [48]:
df.to_csv('Gurgaon_properties_cleaned_v1.csv',index=False)